# Generated by Django 4.1.7 on 2023-03-17 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Academic and Professional', 'Academic and Professional'), ('Community Leadership', 'Community Leadership'), ('Cultural Diversity', 'Cultural Diversity'), ('Greek Life', 'Greek Life'), ('Performing Arts & Media', 'Performing Arts & Media'), ('Religious and Spiritual', 'Religious and Spiritual'), ('Service', 'Service'), ('Social and Recreational', 'Social and Recreational'), ('Special Interest', 'Special Interest')], max_length=35)),
                ('college', models.CharField(choices=[('Capital University', 'Capital University'), ('Central Ohio Technical College', 'Central Ohio Technical College'), ('Columbus College of Art & Design', 'Columbus College of Art & Design'), ('Columbus State Community College', 'Columbus State Community College'), ('Denison University', 'Denison University'), ('Ohio Dominican University', 'Ohio Dominican University'), ('Ohio University', 'Ohio University'), ('Ohio Wesleyan University', 'Ohio Wesleyan University'), ('Otterbein University', 'Otterbein University'), ('The Ohio State University', 'The Ohio State University')], max_length=35)),
                ('redbull_occassion', models.CharField(choices=[('Fitness', 'Fitness'), ('Party & Socializing', 'Party & Socializing'), ('Work', 'Work'), ('Study', 'Study')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=240)),
                ('clubs', models.ManyToManyField(to='redbull_extension.club')),
                ('student_marketers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='contacts',
            field=models.ManyToManyField(to='redbull_extension.person'),
        ),
        migrations.AddField(
            model_name='club',
            name='student_marketers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
