# Generated by Django 4.1.7 on 2023-03-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbull_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('0', 'Academic and Professional'), ('1', 'Community Leadership'), ('2', 'Cultural Diversity'), ('3', 'Greek Life'), ('4', 'Performing Arts & Media'), ('5', 'Religious and Spiritual'), ('6', 'Service'), ('7', 'Social and Recreational'), ('8', 'Special Interest')], max_length=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='college',
            field=models.CharField(choices=[('0', 'Capital University'), ('1', 'Central Ohio Technical College'), ('2', 'Columbus College of Art & Design'), ('3', 'Columbus State Community College'), ('4', 'Denison University'), ('5', 'Ohio Dominican University'), ('6', 'Ohio University'), ('7', 'Ohio Wesleyan University'), ('8', 'Otterbein University'), ('9', 'The Ohio State University')], max_length=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='redbull_occassion',
            field=models.CharField(choices=[('0', 'Fitness'), ('1', 'Party & Socializing'), ('2', 'Work'), ('3', 'Study')], max_length=1),
        ),
    ]
