# Generated by Django 4.1.7 on 2023-03-17 03:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('redbull_extension', '0002_alter_club_category_alter_club_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=240),
        ),
    ]
