# Generated by Django 4.1.7 on 2023-03-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbull_extension', '0003_person_number_alter_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='redbull_occassion',
            new_name='redbull_occasion',
        ),
    ]
